stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: docker.arvancloud.ir/python:slim
  script:
    - ls -al
    - pip install -r requirements.txt
  tags:
    - pet

deploy-job:      
  stage: deploy 
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  tags:
    - deploy
