stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: docker.arvancloud.ir/ubuntu:20.04
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
  tags:
    - pet

unit-test-job:   
  stage: test 
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"
  tags:
    - pet

lint-test-job:   
  stage: test    
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."
  tags:
    - pet

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  tags:
    - deploy
