default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
    - docker info
stages:
  - build
  - test
  - deploy
build:
  stage: build
  before_script: 
    - DOCKER_HOST=tcp://$(ip -4 route show default | cut -d " " -f 3 )
  script:
    - docker info
    - docker build -t my-docker-image .
  tags:
    - pet
deploy-job:      
  stage: deploy 
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  tags:
    - deploy
