services:
  web:
    build:
      context: .

    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"

    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
