# Generated by Django 4.2 on 2023-07-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
