# Generated by Django 4.2 on 2023-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coreuser_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
