# Generated by Django 4.2 on 2023-07-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_coreuser_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
