# Generated by Django 4.2 on 2023-07-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petowner', '0002_remove_petowner_image_alter_petowner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('image', models.ImageField(default='images/pet-logo.png', upload_to='images/')),
                ('serial_number', models.CharField(max_length=255)),
                ('petowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petowner.petowner')),
            ],
        ),
    ]
