# Generated by Django 4.2 on 2023-10-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petowner', '0002_remove_petowner_image_alter_petowner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birthdate', models.DateField()),
                ('image', models.ImageField(default='images/pet-logo.png', upload_to='images/')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('petowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petowner.petowner')),
            ],
        ),
        migrations.CreateModel(
            name='PetTemperatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=10, max_digits=40)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='pet.petmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PetCoordinateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='pet.petmodel')),
            ],
        ),
    ]
