# Generated by Django 4.2 on 2023-08-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
