# Generated by Django 4.2 on 2023-10-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettemperaturemodel',
            name='temperature',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
