# Generated by Django 4.2 on 2023-09-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pettemperaturemodel_petcoordinatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
