# Generated by Django 4.2 on 2023-09-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_alter_pettemperaturemodel_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettemperaturemodel',
            name='temperature',
            field=models.DecimalField(decimal_places=10, max_digits=40),
        ),
    ]
